---
Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/DotPosition:
  EnforcedStyle: trailing

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - thermite-rails.gemspec
    - spec/**/*_spec.rb

Metrics/LineLength:
  Max: 120

Rails:
  Enabled: true

Rails/Output:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '[]'
    '%w': '[]'
    '%W': '[]'

Style/SymbolArray:
  Enabled: true

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - spec/dummy/db/schema.rb
    - vendor/bundle/**/*
  TargetRubyVersion: 2.4
